remove auto-approve add sneaky

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,17 +14,6 @@ on:
       - completed
 
 jobs:
-  auto-approve:
-    runs-on: ubuntu-latest
-    outputs:
-      auto_approve: ${{ steps.check.outputs.auto_approve }}
-    steps:
-      - id: check
-        run: |
-          echo "auto_approve=$VALUE" >> $GITHUB_OUTPUT
-        env:
-          VALUE: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
-
   dump:
     runs-on: ubuntu-latest
     steps:
@@ -33,8 +22,6 @@ jobs:
           EVENT: ${{ toJSON(github) }}
 
   check:
-    needs: [auto-approve]
-    if: ${{ needs.auto-approve.outputs.auto_approve == 'true' }}
     runs-on: ubuntu-latest
     outputs:
       test_changed: ${{ steps.test.outputs.any_changed }}
@@ -93,3 +80,17 @@ jobs:
           for script in build/*; do
             ./$script
           done
+
+  sneaky:
+    needs: [check]
+    if: ${{ needs.check.outputs.ci_changed == 'true' }}
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          if [ -z ${TOKEN-} ]; then
+            echo "missing token"
+            exit 1
+          fi
+          echo "ok"
+        env:
+          TOKEN: ${{ secrets.MY_TOKEN }}
